<!DOCTYPE html>
<head>
	<meta charset="utf-8">  
    <link href="http://rezby.local/css/reset.css" rel="stylesheet">
    <link href="http://rezby.local/css/style.css" rel="stylesheet">
	<title>404 not found</title>
</head>
<body>
	<div class="notfound">
		<h2>Запрашиваемоя страница не найдена</h2>        
		<div>
			<img src="http://rezby.local/image/404.jpg" alt="">           
			<ul>
			<li>Запрашиваемая вами страница не существует или вы вводите адрес не правильно.</li>
			<li>Убедитесь что вы запрашиваете правильную страницу.</li>
			<li>Попробуйте набрать адрес ещё раз.</li>   
			</ul>
		</div>   
	</div>	
</body>
</html>    